# Generated by Django 3.0.3 on 2020-07-23 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
