# Generated by Django 3.0.3 on 2020-07-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20200723_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='value',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
