# Generated by Django 3.0.3 on 2020-07-23 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_order_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='value',
        ),
    ]
